/* eslint-disable */
// @ts-nocheck
/*
* This file is a generated Typescript file for GRPC Gateway, DO NOT MODIFY
*/

export enum FieldBehavior {
  FIELD_BEHAVIOR_UNSPECIFIED = "FIELD_BEHAVIOR_UNSPECIFIED",
  OPTIONAL = "OPTIONAL",
  REQUIRED = "REQUIRED",
  OUTPUT_ONLY = "OUTPUT_ONLY",
  INPUT_ONLY = "INPUT_ONLY",
  IMMUTABLE = "IMMUTABLE",
  UNORDERED_LIST = "UNORDERED_LIST",
  NON_EMPTY_DEFAULT = "NON_EMPTY_DEFAULT",
  IDENTIFIER = "IDENTIFIER",
}