// @generated by protoc-gen-es v2.2.3 with parameter "target=ts,json_types=true"
// @generated from file api/v1/activity_service.proto (package memos.api.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import { file_google_api_annotations } from "../../google/api/annotations_pb";
import { file_google_api_client } from "../../google/api/client_pb";
import { file_google_api_field_behavior } from "../../google/api/field_behavior_pb";
import type { Timestamp, TimestampJson } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file api/v1/activity_service.proto.
 */
export const file_api_v1_activity_service: GenFile = /*@__PURE__*/
  fileDesc("Ch1hcGkvdjEvYWN0aXZpdHlfc2VydmljZS5wcm90bxIMbWVtb3MuYXBpLnYxIq0BCghBY3Rpdml0eRIKCgJpZBgBIAEoBRISCgpjcmVhdG9yX2lkGAIgASgFEgwKBHR5cGUYAyABKAkSDQoFbGV2ZWwYBCABKAkSNAoLY3JlYXRlX3RpbWUYBSABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wQgPgQQMSLgoHcGF5bG9hZBgGIAEoCzIdLm1lbW9zLmFwaS52MS5BY3Rpdml0eVBheWxvYWQiRgoaQWN0aXZpdHlNZW1vQ29tbWVudFBheWxvYWQSDwoHbWVtb19pZBgBIAEoBRIXCg9yZWxhdGVkX21lbW9faWQYAiABKAUiLwocQWN0aXZpdHlWZXJzaW9uVXBkYXRlUGF5bG9hZBIPCgd2ZXJzaW9uGAEgASgJIpUBCg9BY3Rpdml0eVBheWxvYWQSPgoMbWVtb19jb21tZW50GAEgASgLMigubWVtb3MuYXBpLnYxLkFjdGl2aXR5TWVtb0NvbW1lbnRQYXlsb2FkEkIKDnZlcnNpb25fdXBkYXRlGAIgASgLMioubWVtb3MuYXBpLnYxLkFjdGl2aXR5VmVyc2lvblVwZGF0ZVBheWxvYWQiIAoSR2V0QWN0aXZpdHlSZXF1ZXN0EgoKAmlkGAEgASgFMoABCg9BY3Rpdml0eVNlcnZpY2USbQoLR2V0QWN0aXZpdHkSIC5tZW1vcy5hcGkudjEuR2V0QWN0aXZpdHlSZXF1ZXN0GhYubWVtb3MuYXBpLnYxLkFjdGl2aXR5IiTaQQJpZILT5JMCGRIXL2FwaS92MS9hY3Rpdml0aWVzL3tpZH1ChgEKEGNvbS5tZW1vcy5hcGkudjFCFEFjdGl2aXR5U2VydmljZVByb3RvUAFaCmdlbi9hcGkvdjGiAgNNQViqAgxNZW1vcy5BcGkuVjHKAgxNZW1vc1xBcGlcVjHiAhhNZW1vc1xBcGlcVjFcR1BCTWV0YWRhdGHqAg5NZW1vczo6QXBpOjpWMWIGcHJvdG8z", [file_google_api_annotations, file_google_api_client, file_google_api_field_behavior, file_google_protobuf_timestamp]);

/**
 * @generated from message memos.api.v1.Activity
 */
export type Activity = Message<"memos.api.v1.Activity"> & {
  /**
   * The system-generated unique identifier for the activity.
   *
   * @generated from field: int32 id = 1;
   */
  id: number;

  /**
   * The system-generated unique identifier for the user who created the activity.
   *
   * @generated from field: int32 creator_id = 2;
   */
  creatorId: number;

  /**
   * The type of the activity.
   *
   * @generated from field: string type = 3;
   */
  type: string;

  /**
   * The level of the activity.
   *
   * @generated from field: string level = 4;
   */
  level: string;

  /**
   * The create time of the activity.
   *
   * @generated from field: google.protobuf.Timestamp create_time = 5;
   */
  createTime?: Timestamp;

  /**
   * The payload of the activity.
   *
   * @generated from field: memos.api.v1.ActivityPayload payload = 6;
   */
  payload?: ActivityPayload;
};

/**
 * @generated from message memos.api.v1.Activity
 */
export type ActivityJson = {
  /**
   * The system-generated unique identifier for the activity.
   *
   * @generated from field: int32 id = 1;
   */
  id?: number;

  /**
   * The system-generated unique identifier for the user who created the activity.
   *
   * @generated from field: int32 creator_id = 2;
   */
  creatorId?: number;

  /**
   * The type of the activity.
   *
   * @generated from field: string type = 3;
   */
  type?: string;

  /**
   * The level of the activity.
   *
   * @generated from field: string level = 4;
   */
  level?: string;

  /**
   * The create time of the activity.
   *
   * @generated from field: google.protobuf.Timestamp create_time = 5;
   */
  createTime?: TimestampJson;

  /**
   * The payload of the activity.
   *
   * @generated from field: memos.api.v1.ActivityPayload payload = 6;
   */
  payload?: ActivityPayloadJson;
};

/**
 * Describes the message memos.api.v1.Activity.
 * Use `create(ActivitySchema)` to create a new message.
 */
export const ActivitySchema: GenMessage<Activity, ActivityJson> = /*@__PURE__*/
  messageDesc(file_api_v1_activity_service, 0);

/**
 * ActivityMemoCommentPayload represents the payload of a memo comment activity.
 *
 * @generated from message memos.api.v1.ActivityMemoCommentPayload
 */
export type ActivityMemoCommentPayload = Message<"memos.api.v1.ActivityMemoCommentPayload"> & {
  /**
   * The memo id of comment.
   *
   * @generated from field: int32 memo_id = 1;
   */
  memoId: number;

  /**
   * The memo id of related memo.
   *
   * @generated from field: int32 related_memo_id = 2;
   */
  relatedMemoId: number;
};

/**
 * ActivityMemoCommentPayload represents the payload of a memo comment activity.
 *
 * @generated from message memos.api.v1.ActivityMemoCommentPayload
 */
export type ActivityMemoCommentPayloadJson = {
  /**
   * The memo id of comment.
   *
   * @generated from field: int32 memo_id = 1;
   */
  memoId?: number;

  /**
   * The memo id of related memo.
   *
   * @generated from field: int32 related_memo_id = 2;
   */
  relatedMemoId?: number;
};

/**
 * Describes the message memos.api.v1.ActivityMemoCommentPayload.
 * Use `create(ActivityMemoCommentPayloadSchema)` to create a new message.
 */
export const ActivityMemoCommentPayloadSchema: GenMessage<ActivityMemoCommentPayload, ActivityMemoCommentPayloadJson> = /*@__PURE__*/
  messageDesc(file_api_v1_activity_service, 1);

/**
 * @generated from message memos.api.v1.ActivityVersionUpdatePayload
 */
export type ActivityVersionUpdatePayload = Message<"memos.api.v1.ActivityVersionUpdatePayload"> & {
  /**
   * The updated version of memos.
   *
   * @generated from field: string version = 1;
   */
  version: string;
};

/**
 * @generated from message memos.api.v1.ActivityVersionUpdatePayload
 */
export type ActivityVersionUpdatePayloadJson = {
  /**
   * The updated version of memos.
   *
   * @generated from field: string version = 1;
   */
  version?: string;
};

/**
 * Describes the message memos.api.v1.ActivityVersionUpdatePayload.
 * Use `create(ActivityVersionUpdatePayloadSchema)` to create a new message.
 */
export const ActivityVersionUpdatePayloadSchema: GenMessage<ActivityVersionUpdatePayload, ActivityVersionUpdatePayloadJson> = /*@__PURE__*/
  messageDesc(file_api_v1_activity_service, 2);

/**
 * @generated from message memos.api.v1.ActivityPayload
 */
export type ActivityPayload = Message<"memos.api.v1.ActivityPayload"> & {
  /**
   * @generated from field: memos.api.v1.ActivityMemoCommentPayload memo_comment = 1;
   */
  memoComment?: ActivityMemoCommentPayload;

  /**
   * @generated from field: memos.api.v1.ActivityVersionUpdatePayload version_update = 2;
   */
  versionUpdate?: ActivityVersionUpdatePayload;
};

/**
 * @generated from message memos.api.v1.ActivityPayload
 */
export type ActivityPayloadJson = {
  /**
   * @generated from field: memos.api.v1.ActivityMemoCommentPayload memo_comment = 1;
   */
  memoComment?: ActivityMemoCommentPayloadJson;

  /**
   * @generated from field: memos.api.v1.ActivityVersionUpdatePayload version_update = 2;
   */
  versionUpdate?: ActivityVersionUpdatePayloadJson;
};

/**
 * Describes the message memos.api.v1.ActivityPayload.
 * Use `create(ActivityPayloadSchema)` to create a new message.
 */
export const ActivityPayloadSchema: GenMessage<ActivityPayload, ActivityPayloadJson> = /*@__PURE__*/
  messageDesc(file_api_v1_activity_service, 3);

/**
 * @generated from message memos.api.v1.GetActivityRequest
 */
export type GetActivityRequest = Message<"memos.api.v1.GetActivityRequest"> & {
  /**
   * The system-generated unique identifier for the activity.
   *
   * @generated from field: int32 id = 1;
   */
  id: number;
};

/**
 * @generated from message memos.api.v1.GetActivityRequest
 */
export type GetActivityRequestJson = {
  /**
   * The system-generated unique identifier for the activity.
   *
   * @generated from field: int32 id = 1;
   */
  id?: number;
};

/**
 * Describes the message memos.api.v1.GetActivityRequest.
 * Use `create(GetActivityRequestSchema)` to create a new message.
 */
export const GetActivityRequestSchema: GenMessage<GetActivityRequest, GetActivityRequestJson> = /*@__PURE__*/
  messageDesc(file_api_v1_activity_service, 4);

/**
 * @generated from service memos.api.v1.ActivityService
 */
export const ActivityService: GenService<{
  /**
   * GetActivity returns the activity with the given id.
   *
   * @generated from rpc memos.api.v1.ActivityService.GetActivity
   */
  getActivity: {
    methodKind: "unary";
    input: typeof GetActivityRequestSchema;
    output: typeof ActivitySchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_api_v1_activity_service, 0);

