// @generated by protoc-gen-es v2.2.3 with parameter "target=ts,json_types=true"
// @generated from file api/v1/auth_service.proto (package memos.api.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { User, UserJson, UserSchema } from "./user_service_pb";
import { file_api_v1_user_service } from "./user_service_pb";
import { file_google_api_annotations } from "../../google/api/annotations_pb";
import type { EmptySchema } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_empty } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file api/v1/auth_service.proto.
 */
export const file_api_v1_auth_service: GenFile = /*@__PURE__*/
  fileDesc("ChlhcGkvdjEvYXV0aF9zZXJ2aWNlLnByb3RvEgxtZW1vcy5hcGkudjEiFgoUR2V0QXV0aFN0YXR1c1JlcXVlc3QiOQoVR2V0QXV0aFN0YXR1c1Jlc3BvbnNlEiAKBHVzZXIYASABKAsyEi5tZW1vcy5hcGkudjEuVXNlciJJCg1TaWduSW5SZXF1ZXN0EhAKCHVzZXJuYW1lGAEgASgJEhAKCHBhc3N3b3JkGAIgASgJEhQKDG5ldmVyX2V4cGlyZRgDIAEoCCJKChRTaWduSW5XaXRoU1NPUmVxdWVzdBIOCgZpZHBfaWQYASABKAUSDAoEY29kZRgCIAEoCRIUCgxyZWRpcmVjdF91cmkYAyABKAkiMwoNU2lnblVwUmVxdWVzdBIQCgh1c2VybmFtZRgBIAEoCRIQCghwYXNzd29yZBgCIAEoCSIQCg5TaWduT3V0UmVxdWVzdDLsAwoLQXV0aFNlcnZpY2USZAoNR2V0QXV0aFN0YXR1cxIiLm1lbW9zLmFwaS52MS5HZXRBdXRoU3RhdHVzUmVxdWVzdBoSLm1lbW9zLmFwaS52MS5Vc2VyIhuC0+STAhUiEy9hcGkvdjEvYXV0aC9zdGF0dXMSVgoGU2lnbkluEhsubWVtb3MuYXBpLnYxLlNpZ25JblJlcXVlc3QaEi5tZW1vcy5hcGkudjEuVXNlciIbgtPkkwIVIhMvYXBpL3YxL2F1dGgvc2lnbmluEmgKDVNpZ25JbldpdGhTU08SIi5tZW1vcy5hcGkudjEuU2lnbkluV2l0aFNTT1JlcXVlc3QaEi5tZW1vcy5hcGkudjEuVXNlciIfgtPkkwIZIhcvYXBpL3YxL2F1dGgvc2lnbmluL3NzbxJWCgZTaWduVXASGy5tZW1vcy5hcGkudjEuU2lnblVwUmVxdWVzdBoSLm1lbW9zLmFwaS52MS5Vc2VyIhuC0+STAhUiEy9hcGkvdjEvYXV0aC9zaWdudXASXQoHU2lnbk91dBIcLm1lbW9zLmFwaS52MS5TaWduT3V0UmVxdWVzdBoWLmdvb2dsZS5wcm90b2J1Zi5FbXB0eSIcgtPkkwIWIhQvYXBpL3YxL2F1dGgvc2lnbm91dEKCAQoQY29tLm1lbW9zLmFwaS52MUIQQXV0aFNlcnZpY2VQcm90b1ABWgpnZW4vYXBpL3YxogIDTUFYqgIMTWVtb3MuQXBpLlYxygIMTWVtb3NcQXBpXFYx4gIYTWVtb3NcQXBpXFYxXEdQQk1ldGFkYXRh6gIOTWVtb3M6OkFwaTo6VjFiBnByb3RvMw", [file_api_v1_user_service, file_google_api_annotations, file_google_protobuf_empty]);

/**
 * @generated from message memos.api.v1.GetAuthStatusRequest
 */
export type GetAuthStatusRequest = Message<"memos.api.v1.GetAuthStatusRequest"> & {
};

/**
 * @generated from message memos.api.v1.GetAuthStatusRequest
 */
export type GetAuthStatusRequestJson = {
};

/**
 * Describes the message memos.api.v1.GetAuthStatusRequest.
 * Use `create(GetAuthStatusRequestSchema)` to create a new message.
 */
export const GetAuthStatusRequestSchema: GenMessage<GetAuthStatusRequest, GetAuthStatusRequestJson> = /*@__PURE__*/
  messageDesc(file_api_v1_auth_service, 0);

/**
 * @generated from message memos.api.v1.GetAuthStatusResponse
 */
export type GetAuthStatusResponse = Message<"memos.api.v1.GetAuthStatusResponse"> & {
  /**
   * @generated from field: memos.api.v1.User user = 1;
   */
  user?: User;
};

/**
 * @generated from message memos.api.v1.GetAuthStatusResponse
 */
export type GetAuthStatusResponseJson = {
  /**
   * @generated from field: memos.api.v1.User user = 1;
   */
  user?: UserJson;
};

/**
 * Describes the message memos.api.v1.GetAuthStatusResponse.
 * Use `create(GetAuthStatusResponseSchema)` to create a new message.
 */
export const GetAuthStatusResponseSchema: GenMessage<GetAuthStatusResponse, GetAuthStatusResponseJson> = /*@__PURE__*/
  messageDesc(file_api_v1_auth_service, 1);

/**
 * @generated from message memos.api.v1.SignInRequest
 */
export type SignInRequest = Message<"memos.api.v1.SignInRequest"> & {
  /**
   * The username to sign in with.
   *
   * @generated from field: string username = 1;
   */
  username: string;

  /**
   * The password to sign in with.
   *
   * @generated from field: string password = 2;
   */
  password: string;

  /**
   * Whether the session should never expire.
   *
   * @generated from field: bool never_expire = 3;
   */
  neverExpire: boolean;
};

/**
 * @generated from message memos.api.v1.SignInRequest
 */
export type SignInRequestJson = {
  /**
   * The username to sign in with.
   *
   * @generated from field: string username = 1;
   */
  username?: string;

  /**
   * The password to sign in with.
   *
   * @generated from field: string password = 2;
   */
  password?: string;

  /**
   * Whether the session should never expire.
   *
   * @generated from field: bool never_expire = 3;
   */
  neverExpire?: boolean;
};

/**
 * Describes the message memos.api.v1.SignInRequest.
 * Use `create(SignInRequestSchema)` to create a new message.
 */
export const SignInRequestSchema: GenMessage<SignInRequest, SignInRequestJson> = /*@__PURE__*/
  messageDesc(file_api_v1_auth_service, 2);

/**
 * @generated from message memos.api.v1.SignInWithSSORequest
 */
export type SignInWithSSORequest = Message<"memos.api.v1.SignInWithSSORequest"> & {
  /**
   * The ID of the SSO provider.
   *
   * @generated from field: int32 idp_id = 1;
   */
  idpId: number;

  /**
   * The code to sign in with.
   *
   * @generated from field: string code = 2;
   */
  code: string;

  /**
   * The redirect URI.
   *
   * @generated from field: string redirect_uri = 3;
   */
  redirectUri: string;
};

/**
 * @generated from message memos.api.v1.SignInWithSSORequest
 */
export type SignInWithSSORequestJson = {
  /**
   * The ID of the SSO provider.
   *
   * @generated from field: int32 idp_id = 1;
   */
  idpId?: number;

  /**
   * The code to sign in with.
   *
   * @generated from field: string code = 2;
   */
  code?: string;

  /**
   * The redirect URI.
   *
   * @generated from field: string redirect_uri = 3;
   */
  redirectUri?: string;
};

/**
 * Describes the message memos.api.v1.SignInWithSSORequest.
 * Use `create(SignInWithSSORequestSchema)` to create a new message.
 */
export const SignInWithSSORequestSchema: GenMessage<SignInWithSSORequest, SignInWithSSORequestJson> = /*@__PURE__*/
  messageDesc(file_api_v1_auth_service, 3);

/**
 * @generated from message memos.api.v1.SignUpRequest
 */
export type SignUpRequest = Message<"memos.api.v1.SignUpRequest"> & {
  /**
   * The username to sign up with.
   *
   * @generated from field: string username = 1;
   */
  username: string;

  /**
   * The password to sign up with.
   *
   * @generated from field: string password = 2;
   */
  password: string;
};

/**
 * @generated from message memos.api.v1.SignUpRequest
 */
export type SignUpRequestJson = {
  /**
   * The username to sign up with.
   *
   * @generated from field: string username = 1;
   */
  username?: string;

  /**
   * The password to sign up with.
   *
   * @generated from field: string password = 2;
   */
  password?: string;
};

/**
 * Describes the message memos.api.v1.SignUpRequest.
 * Use `create(SignUpRequestSchema)` to create a new message.
 */
export const SignUpRequestSchema: GenMessage<SignUpRequest, SignUpRequestJson> = /*@__PURE__*/
  messageDesc(file_api_v1_auth_service, 4);

/**
 * @generated from message memos.api.v1.SignOutRequest
 */
export type SignOutRequest = Message<"memos.api.v1.SignOutRequest"> & {
};

/**
 * @generated from message memos.api.v1.SignOutRequest
 */
export type SignOutRequestJson = {
};

/**
 * Describes the message memos.api.v1.SignOutRequest.
 * Use `create(SignOutRequestSchema)` to create a new message.
 */
export const SignOutRequestSchema: GenMessage<SignOutRequest, SignOutRequestJson> = /*@__PURE__*/
  messageDesc(file_api_v1_auth_service, 5);

/**
 * @generated from service memos.api.v1.AuthService
 */
export const AuthService: GenService<{
  /**
   * GetAuthStatus returns the current auth status of the user.
   *
   * @generated from rpc memos.api.v1.AuthService.GetAuthStatus
   */
  getAuthStatus: {
    methodKind: "unary";
    input: typeof GetAuthStatusRequestSchema;
    output: typeof UserSchema;
  },
  /**
   * SignIn signs in the user with the given username and password.
   *
   * @generated from rpc memos.api.v1.AuthService.SignIn
   */
  signIn: {
    methodKind: "unary";
    input: typeof SignInRequestSchema;
    output: typeof UserSchema;
  },
  /**
   * SignInWithSSO signs in the user with the given SSO code.
   *
   * @generated from rpc memos.api.v1.AuthService.SignInWithSSO
   */
  signInWithSSO: {
    methodKind: "unary";
    input: typeof SignInWithSSORequestSchema;
    output: typeof UserSchema;
  },
  /**
   * SignUp signs up the user with the given username and password.
   *
   * @generated from rpc memos.api.v1.AuthService.SignUp
   */
  signUp: {
    methodKind: "unary";
    input: typeof SignUpRequestSchema;
    output: typeof UserSchema;
  },
  /**
   * SignOut signs out the user.
   *
   * @generated from rpc memos.api.v1.AuthService.SignOut
   */
  signOut: {
    methodKind: "unary";
    input: typeof SignOutRequestSchema;
    output: typeof EmptySchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_api_v1_auth_service, 0);

