// @generated by protoc-gen-es v2.2.3 with parameter "target=ts,json_types=true"
// @generated from file api/v1/inbox_service.proto (package memos.api.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { enumDesc, fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import { file_google_api_annotations } from "../../google/api/annotations_pb";
import { file_google_api_client } from "../../google/api/client_pb";
import type { EmptySchema, FieldMask, FieldMaskJson, Timestamp, TimestampJson } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_empty, file_google_protobuf_field_mask, file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file api/v1/inbox_service.proto.
 */
export const file_api_v1_inbox_service: GenFile = /*@__PURE__*/
  fileDesc("ChphcGkvdjEvaW5ib3hfc2VydmljZS5wcm90bxIMbWVtb3MuYXBpLnYxIrwCCgVJbmJveBIMCgRuYW1lGAEgASgJEg4KBnNlbmRlchgCIAEoCRIQCghyZWNlaXZlchgDIAEoCRIqCgZzdGF0dXMYBCABKA4yGi5tZW1vcy5hcGkudjEuSW5ib3guU3RhdHVzEi8KC2NyZWF0ZV90aW1lGAUgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBImCgR0eXBlGAYgASgOMhgubWVtb3MuYXBpLnYxLkluYm94LlR5cGUiOgoGU3RhdHVzEhYKElNUQVRVU19VTlNQRUNJRklFRBAAEgoKBlVOUkVBRBABEgwKCEFSQ0hJVkVEEAIiQgoEVHlwZRIUChBUWVBFX1VOU1BFQ0lGSUVEEAASEAoMTUVNT19DT01NRU5UEAESEgoOVkVSU0lPTl9VUERBVEUQAiIiChJMaXN0SW5ib3hlc1JlcXVlc3QSDAoEdXNlchgBIAEoCSI7ChNMaXN0SW5ib3hlc1Jlc3BvbnNlEiQKB2luYm94ZXMYASADKAsyEy5tZW1vcy5hcGkudjEuSW5ib3giaQoSVXBkYXRlSW5ib3hSZXF1ZXN0EiIKBWluYm94GAEgASgLMhMubWVtb3MuYXBpLnYxLkluYm94Ei8KC3VwZGF0ZV9tYXNrGAIgASgLMhouZ29vZ2xlLnByb3RvYnVmLkZpZWxkTWFzayIiChJEZWxldGVJbmJveFJlcXVlc3QSDAoEbmFtZRgBIAEoCTL3AgoMSW5ib3hTZXJ2aWNlEmsKC0xpc3RJbmJveGVzEiAubWVtb3MuYXBpLnYxLkxpc3RJbmJveGVzUmVxdWVzdBohLm1lbW9zLmFwaS52MS5MaXN0SW5ib3hlc1Jlc3BvbnNlIheC0+STAhESDy9hcGkvdjEvaW5ib3hlcxKHAQoLVXBkYXRlSW5ib3gSIC5tZW1vcy5hcGkudjEuVXBkYXRlSW5ib3hSZXF1ZXN0GhMubWVtb3MuYXBpLnYxLkluYm94IkHaQRFpbmJveCx1cGRhdGVfbWFza4LT5JMCJzoFaW5ib3gyHi9hcGkvdjEve2luYm94Lm5hbWU9aW5ib3hlcy8qfRJwCgtEZWxldGVJbmJveBIgLm1lbW9zLmFwaS52MS5EZWxldGVJbmJveFJlcXVlc3QaFi5nb29nbGUucHJvdG9idWYuRW1wdHkiJ9pBBG5hbWWC0+STAhoqGC9hcGkvdjEve25hbWU9aW5ib3hlcy8qfUKDAQoQY29tLm1lbW9zLmFwaS52MUIRSW5ib3hTZXJ2aWNlUHJvdG9QAVoKZ2VuL2FwaS92MaICA01BWKoCDE1lbW9zLkFwaS5WMcoCDE1lbW9zXEFwaVxWMeICGE1lbW9zXEFwaVxWMVxHUEJNZXRhZGF0YeoCDk1lbW9zOjpBcGk6OlYxYgZwcm90bzM", [file_google_api_annotations, file_google_api_client, file_google_protobuf_empty, file_google_protobuf_field_mask, file_google_protobuf_timestamp]);

/**
 * @generated from message memos.api.v1.Inbox
 */
export type Inbox = Message<"memos.api.v1.Inbox"> & {
  /**
   * The name of the inbox.
   * Format: inboxes/{id}
   *
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * Format: users/{id}
   *
   * @generated from field: string sender = 2;
   */
  sender: string;

  /**
   * Format: users/{id}
   *
   * @generated from field: string receiver = 3;
   */
  receiver: string;

  /**
   * @generated from field: memos.api.v1.Inbox.Status status = 4;
   */
  status: Inbox_Status;

  /**
   * @generated from field: google.protobuf.Timestamp create_time = 5;
   */
  createTime?: Timestamp;

  /**
   * @generated from field: memos.api.v1.Inbox.Type type = 6;
   */
  type: Inbox_Type;
};

/**
 * @generated from message memos.api.v1.Inbox
 */
export type InboxJson = {
  /**
   * The name of the inbox.
   * Format: inboxes/{id}
   *
   * @generated from field: string name = 1;
   */
  name?: string;

  /**
   * Format: users/{id}
   *
   * @generated from field: string sender = 2;
   */
  sender?: string;

  /**
   * Format: users/{id}
   *
   * @generated from field: string receiver = 3;
   */
  receiver?: string;

  /**
   * @generated from field: memos.api.v1.Inbox.Status status = 4;
   */
  status?: Inbox_StatusJson;

  /**
   * @generated from field: google.protobuf.Timestamp create_time = 5;
   */
  createTime?: TimestampJson;

  /**
   * @generated from field: memos.api.v1.Inbox.Type type = 6;
   */
  type?: Inbox_TypeJson;
};

/**
 * Describes the message memos.api.v1.Inbox.
 * Use `create(InboxSchema)` to create a new message.
 */
export const InboxSchema: GenMessage<Inbox, InboxJson> = /*@__PURE__*/
  messageDesc(file_api_v1_inbox_service, 0);

/**
 * @generated from enum memos.api.v1.Inbox.Status
 */
export enum Inbox_Status {
  /**
   * @generated from enum value: STATUS_UNSPECIFIED = 0;
   */
  STATUS_UNSPECIFIED = 0,

  /**
   * @generated from enum value: UNREAD = 1;
   */
  UNREAD = 1,

  /**
   * @generated from enum value: ARCHIVED = 2;
   */
  ARCHIVED = 2,
}

/**
 * @generated from enum memos.api.v1.Inbox.Status
 */
export type Inbox_StatusJson = "STATUS_UNSPECIFIED" | "UNREAD" | "ARCHIVED";

/**
 * Describes the enum memos.api.v1.Inbox.Status.
 */
export const Inbox_StatusSchema: GenEnum<Inbox_Status, Inbox_StatusJson> = /*@__PURE__*/
  enumDesc(file_api_v1_inbox_service, 0, 0);

/**
 * @generated from enum memos.api.v1.Inbox.Type
 */
export enum Inbox_Type {
  /**
   * @generated from enum value: TYPE_UNSPECIFIED = 0;
   */
  TYPE_UNSPECIFIED = 0,

  /**
   * @generated from enum value: MEMO_COMMENT = 1;
   */
  MEMO_COMMENT = 1,

  /**
   * @generated from enum value: VERSION_UPDATE = 2;
   */
  VERSION_UPDATE = 2,
}

/**
 * @generated from enum memos.api.v1.Inbox.Type
 */
export type Inbox_TypeJson = "TYPE_UNSPECIFIED" | "MEMO_COMMENT" | "VERSION_UPDATE";

/**
 * Describes the enum memos.api.v1.Inbox.Type.
 */
export const Inbox_TypeSchema: GenEnum<Inbox_Type, Inbox_TypeJson> = /*@__PURE__*/
  enumDesc(file_api_v1_inbox_service, 0, 1);

/**
 * @generated from message memos.api.v1.ListInboxesRequest
 */
export type ListInboxesRequest = Message<"memos.api.v1.ListInboxesRequest"> & {
  /**
   * Format: users/{id}
   *
   * @generated from field: string user = 1;
   */
  user: string;
};

/**
 * @generated from message memos.api.v1.ListInboxesRequest
 */
export type ListInboxesRequestJson = {
  /**
   * Format: users/{id}
   *
   * @generated from field: string user = 1;
   */
  user?: string;
};

/**
 * Describes the message memos.api.v1.ListInboxesRequest.
 * Use `create(ListInboxesRequestSchema)` to create a new message.
 */
export const ListInboxesRequestSchema: GenMessage<ListInboxesRequest, ListInboxesRequestJson> = /*@__PURE__*/
  messageDesc(file_api_v1_inbox_service, 1);

/**
 * @generated from message memos.api.v1.ListInboxesResponse
 */
export type ListInboxesResponse = Message<"memos.api.v1.ListInboxesResponse"> & {
  /**
   * @generated from field: repeated memos.api.v1.Inbox inboxes = 1;
   */
  inboxes: Inbox[];
};

/**
 * @generated from message memos.api.v1.ListInboxesResponse
 */
export type ListInboxesResponseJson = {
  /**
   * @generated from field: repeated memos.api.v1.Inbox inboxes = 1;
   */
  inboxes?: InboxJson[];
};

/**
 * Describes the message memos.api.v1.ListInboxesResponse.
 * Use `create(ListInboxesResponseSchema)` to create a new message.
 */
export const ListInboxesResponseSchema: GenMessage<ListInboxesResponse, ListInboxesResponseJson> = /*@__PURE__*/
  messageDesc(file_api_v1_inbox_service, 2);

/**
 * @generated from message memos.api.v1.UpdateInboxRequest
 */
export type UpdateInboxRequest = Message<"memos.api.v1.UpdateInboxRequest"> & {
  /**
   * @generated from field: memos.api.v1.Inbox inbox = 1;
   */
  inbox?: Inbox;

  /**
   * @generated from field: google.protobuf.FieldMask update_mask = 2;
   */
  updateMask?: FieldMask;
};

/**
 * @generated from message memos.api.v1.UpdateInboxRequest
 */
export type UpdateInboxRequestJson = {
  /**
   * @generated from field: memos.api.v1.Inbox inbox = 1;
   */
  inbox?: InboxJson;

  /**
   * @generated from field: google.protobuf.FieldMask update_mask = 2;
   */
  updateMask?: FieldMaskJson;
};

/**
 * Describes the message memos.api.v1.UpdateInboxRequest.
 * Use `create(UpdateInboxRequestSchema)` to create a new message.
 */
export const UpdateInboxRequestSchema: GenMessage<UpdateInboxRequest, UpdateInboxRequestJson> = /*@__PURE__*/
  messageDesc(file_api_v1_inbox_service, 3);

/**
 * @generated from message memos.api.v1.DeleteInboxRequest
 */
export type DeleteInboxRequest = Message<"memos.api.v1.DeleteInboxRequest"> & {
  /**
   * The name of the inbox to delete.
   * Format: inboxes/{id}
   *
   * @generated from field: string name = 1;
   */
  name: string;
};

/**
 * @generated from message memos.api.v1.DeleteInboxRequest
 */
export type DeleteInboxRequestJson = {
  /**
   * The name of the inbox to delete.
   * Format: inboxes/{id}
   *
   * @generated from field: string name = 1;
   */
  name?: string;
};

/**
 * Describes the message memos.api.v1.DeleteInboxRequest.
 * Use `create(DeleteInboxRequestSchema)` to create a new message.
 */
export const DeleteInboxRequestSchema: GenMessage<DeleteInboxRequest, DeleteInboxRequestJson> = /*@__PURE__*/
  messageDesc(file_api_v1_inbox_service, 4);

/**
 * @generated from service memos.api.v1.InboxService
 */
export const InboxService: GenService<{
  /**
   * ListInboxes lists inboxes for a user.
   *
   * @generated from rpc memos.api.v1.InboxService.ListInboxes
   */
  listInboxes: {
    methodKind: "unary";
    input: typeof ListInboxesRequestSchema;
    output: typeof ListInboxesResponseSchema;
  },
  /**
   * UpdateInbox updates an inbox.
   *
   * @generated from rpc memos.api.v1.InboxService.UpdateInbox
   */
  updateInbox: {
    methodKind: "unary";
    input: typeof UpdateInboxRequestSchema;
    output: typeof InboxSchema;
  },
  /**
   * DeleteInbox deletes an inbox.
   *
   * @generated from rpc memos.api.v1.InboxService.DeleteInbox
   */
  deleteInbox: {
    methodKind: "unary";
    input: typeof DeleteInboxRequestSchema;
    output: typeof EmptySchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_api_v1_inbox_service, 0);

