// @generated by protoc-gen-es v2.2.3 with parameter "target=ts,json_types=true"
// @generated from file api/v1/reaction_service.proto (package memos.api.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file api/v1/reaction_service.proto.
 */
export const file_api_v1_reaction_service: GenFile = /*@__PURE__*/
  fileDesc("Ch1hcGkvdjEvcmVhY3Rpb25fc2VydmljZS5wcm90bxIMbWVtb3MuYXBpLnYxIrsCCghSZWFjdGlvbhIKCgJpZBgBIAEoBRIPCgdjcmVhdG9yGAIgASgJEhIKCmNvbnRlbnRfaWQYAyABKAkSMgoNcmVhY3Rpb25fdHlwZRgEIAEoDjIbLm1lbW9zLmFwaS52MS5SZWFjdGlvbi5UeXBlIskBCgRUeXBlEhQKEFRZUEVfVU5TUEVDSUZJRUQQABINCglUSFVNQlNfVVAQARIPCgtUSFVNQlNfRE9XThACEgkKBUhFQVJUEAMSCAoERklSRRAEEhIKDkNMQVBQSU5HX0hBTkRTEAUSCQoFTEFVR0gQBhILCgdPS19IQU5EEAcSCgoGUk9DS0VUEAgSCAoERVlFUxAJEhEKDVRISU5LSU5HX0ZBQ0UQChIOCgpDTE9XTl9GQUNFEAsSEQoNUVVFU1RJT05fTUFSSxAMQoYBChBjb20ubWVtb3MuYXBpLnYxQhRSZWFjdGlvblNlcnZpY2VQcm90b1ABWgpnZW4vYXBpL3YxogIDTUFYqgIMTWVtb3MuQXBpLlYxygIMTWVtb3NcQXBpXFYx4gIYTWVtb3NcQXBpXFYxXEdQQk1ldGFkYXRh6gIOTWVtb3M6OkFwaTo6VjFiBnByb3RvMw");

/**
 * @generated from message memos.api.v1.Reaction
 */
export type Reaction = Message<"memos.api.v1.Reaction"> & {
  /**
   * @generated from field: int32 id = 1;
   */
  id: number;

  /**
   * The name of the creator.
   * Format: users/{id}
   *
   * @generated from field: string creator = 2;
   */
  creator: string;

  /**
   * @generated from field: string content_id = 3;
   */
  contentId: string;

  /**
   * @generated from field: memos.api.v1.Reaction.Type reaction_type = 4;
   */
  reactionType: Reaction_Type;
};

/**
 * @generated from message memos.api.v1.Reaction
 */
export type ReactionJson = {
  /**
   * @generated from field: int32 id = 1;
   */
  id?: number;

  /**
   * The name of the creator.
   * Format: users/{id}
   *
   * @generated from field: string creator = 2;
   */
  creator?: string;

  /**
   * @generated from field: string content_id = 3;
   */
  contentId?: string;

  /**
   * @generated from field: memos.api.v1.Reaction.Type reaction_type = 4;
   */
  reactionType?: Reaction_TypeJson;
};

/**
 * Describes the message memos.api.v1.Reaction.
 * Use `create(ReactionSchema)` to create a new message.
 */
export const ReactionSchema: GenMessage<Reaction, ReactionJson> = /*@__PURE__*/
  messageDesc(file_api_v1_reaction_service, 0);

/**
 * @generated from enum memos.api.v1.Reaction.Type
 */
export enum Reaction_Type {
  /**
   * @generated from enum value: TYPE_UNSPECIFIED = 0;
   */
  TYPE_UNSPECIFIED = 0,

  /**
   * @generated from enum value: THUMBS_UP = 1;
   */
  THUMBS_UP = 1,

  /**
   * @generated from enum value: THUMBS_DOWN = 2;
   */
  THUMBS_DOWN = 2,

  /**
   * @generated from enum value: HEART = 3;
   */
  HEART = 3,

  /**
   * @generated from enum value: FIRE = 4;
   */
  FIRE = 4,

  /**
   * @generated from enum value: CLAPPING_HANDS = 5;
   */
  CLAPPING_HANDS = 5,

  /**
   * @generated from enum value: LAUGH = 6;
   */
  LAUGH = 6,

  /**
   * @generated from enum value: OK_HAND = 7;
   */
  OK_HAND = 7,

  /**
   * @generated from enum value: ROCKET = 8;
   */
  ROCKET = 8,

  /**
   * @generated from enum value: EYES = 9;
   */
  EYES = 9,

  /**
   * @generated from enum value: THINKING_FACE = 10;
   */
  THINKING_FACE = 10,

  /**
   * @generated from enum value: CLOWN_FACE = 11;
   */
  CLOWN_FACE = 11,

  /**
   * @generated from enum value: QUESTION_MARK = 12;
   */
  QUESTION_MARK = 12,
}

/**
 * @generated from enum memos.api.v1.Reaction.Type
 */
export type Reaction_TypeJson = "TYPE_UNSPECIFIED" | "THUMBS_UP" | "THUMBS_DOWN" | "HEART" | "FIRE" | "CLAPPING_HANDS" | "LAUGH" | "OK_HAND" | "ROCKET" | "EYES" | "THINKING_FACE" | "CLOWN_FACE" | "QUESTION_MARK";

/**
 * Describes the enum memos.api.v1.Reaction.Type.
 */
export const Reaction_TypeSchema: GenEnum<Reaction_Type, Reaction_TypeJson> = /*@__PURE__*/
  enumDesc(file_api_v1_reaction_service, 0, 0);

