// @generated by protoc-gen-es v2.2.3 with parameter "target=ts,json_types=true"
// @generated from file api/v1/webhook_service.proto (package memos.api.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { RowStatus, RowStatusJson } from "./common_pb";
import { file_api_v1_common } from "./common_pb";
import { file_google_api_annotations } from "../../google/api/annotations_pb";
import { file_google_api_client } from "../../google/api/client_pb";
import type { EmptySchema, FieldMask, FieldMaskJson, Timestamp, TimestampJson } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_empty, file_google_protobuf_field_mask, file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file api/v1/webhook_service.proto.
 */
export const file_api_v1_webhook_service: GenFile = /*@__PURE__*/
  fileDesc("ChxhcGkvdjEvd2ViaG9va19zZXJ2aWNlLnByb3RvEgxtZW1vcy5hcGkudjEi1QEKB1dlYmhvb2sSCgoCaWQYASABKAUSEgoKY3JlYXRvcl9pZBgCIAEoBRIwCgxjcmVhdGVkX3RpbWUYAyABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wEjAKDHVwZGF0ZWRfdGltZRgEIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASKwoKcm93X3N0YXR1cxgFIAEoDjIXLm1lbW9zLmFwaS52MS5Sb3dTdGF0dXMSDAoEbmFtZRgGIAEoCRILCgN1cmwYByABKAkiMQoUQ3JlYXRlV2ViaG9va1JlcXVlc3QSDAoEbmFtZRgBIAEoCRILCgN1cmwYAiABKAkiHwoRR2V0V2ViaG9va1JlcXVlc3QSCgoCaWQYASABKAUiKQoTTGlzdFdlYmhvb2tzUmVxdWVzdBISCgpjcmVhdG9yX2lkGAEgASgFIj8KFExpc3RXZWJob29rc1Jlc3BvbnNlEicKCHdlYmhvb2tzGAEgAygLMhUubWVtb3MuYXBpLnYxLldlYmhvb2sibwoUVXBkYXRlV2ViaG9va1JlcXVlc3QSJgoHd2ViaG9vaxgBIAEoCzIVLm1lbW9zLmFwaS52MS5XZWJob29rEi8KC3VwZGF0ZV9tYXNrGAIgASgLMhouZ29vZ2xlLnByb3RvYnVmLkZpZWxkTWFzayIiChREZWxldGVXZWJob29rUmVxdWVzdBIKCgJpZBgBIAEoBTLYBAoOV2ViaG9va1NlcnZpY2USZwoNQ3JlYXRlV2ViaG9vaxIiLm1lbW9zLmFwaS52MS5DcmVhdGVXZWJob29rUmVxdWVzdBoVLm1lbW9zLmFwaS52MS5XZWJob29rIhuC0+STAhU6ASoiEC9hcGkvdjEvd2ViaG9va3MSaAoKR2V0V2ViaG9vaxIfLm1lbW9zLmFwaS52MS5HZXRXZWJob29rUmVxdWVzdBoVLm1lbW9zLmFwaS52MS5XZWJob29rIiLaQQJpZILT5JMCFxIVL2FwaS92MS93ZWJob29rcy97aWR9Em8KDExpc3RXZWJob29rcxIhLm1lbW9zLmFwaS52MS5MaXN0V2ViaG9va3NSZXF1ZXN0GiIubWVtb3MuYXBpLnYxLkxpc3RXZWJob29rc1Jlc3BvbnNlIhiC0+STAhISEC9hcGkvdjEvd2ViaG9va3MSkAEKDVVwZGF0ZVdlYmhvb2sSIi5tZW1vcy5hcGkudjEuVXBkYXRlV2ViaG9va1JlcXVlc3QaFS5tZW1vcy5hcGkudjEuV2ViaG9vayJE2kETd2ViaG9vayx1cGRhdGVfbWFza4LT5JMCKDoHd2ViaG9vazIdL2FwaS92MS93ZWJob29rcy97d2ViaG9vay5pZH0SbwoNRGVsZXRlV2ViaG9vaxIiLm1lbW9zLmFwaS52MS5EZWxldGVXZWJob29rUmVxdWVzdBoWLmdvb2dsZS5wcm90b2J1Zi5FbXB0eSIi2kECaWSC0+STAhcqFS9hcGkvdjEvd2ViaG9va3Mve2lkfUKFAQoQY29tLm1lbW9zLmFwaS52MUITV2ViaG9va1NlcnZpY2VQcm90b1ABWgpnZW4vYXBpL3YxogIDTUFYqgIMTWVtb3MuQXBpLlYxygIMTWVtb3NcQXBpXFYx4gIYTWVtb3NcQXBpXFYxXEdQQk1ldGFkYXRh6gIOTWVtb3M6OkFwaTo6VjFiBnByb3RvMw", [file_api_v1_common, file_google_api_annotations, file_google_api_client, file_google_protobuf_empty, file_google_protobuf_field_mask, file_google_protobuf_timestamp]);

/**
 * @generated from message memos.api.v1.Webhook
 */
export type Webhook = Message<"memos.api.v1.Webhook"> & {
  /**
   * @generated from field: int32 id = 1;
   */
  id: number;

  /**
   * @generated from field: int32 creator_id = 2;
   */
  creatorId: number;

  /**
   * @generated from field: google.protobuf.Timestamp created_time = 3;
   */
  createdTime?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp updated_time = 4;
   */
  updatedTime?: Timestamp;

  /**
   * @generated from field: memos.api.v1.RowStatus row_status = 5;
   */
  rowStatus: RowStatus;

  /**
   * @generated from field: string name = 6;
   */
  name: string;

  /**
   * @generated from field: string url = 7;
   */
  url: string;
};

/**
 * @generated from message memos.api.v1.Webhook
 */
export type WebhookJson = {
  /**
   * @generated from field: int32 id = 1;
   */
  id?: number;

  /**
   * @generated from field: int32 creator_id = 2;
   */
  creatorId?: number;

  /**
   * @generated from field: google.protobuf.Timestamp created_time = 3;
   */
  createdTime?: TimestampJson;

  /**
   * @generated from field: google.protobuf.Timestamp updated_time = 4;
   */
  updatedTime?: TimestampJson;

  /**
   * @generated from field: memos.api.v1.RowStatus row_status = 5;
   */
  rowStatus?: RowStatusJson;

  /**
   * @generated from field: string name = 6;
   */
  name?: string;

  /**
   * @generated from field: string url = 7;
   */
  url?: string;
};

/**
 * Describes the message memos.api.v1.Webhook.
 * Use `create(WebhookSchema)` to create a new message.
 */
export const WebhookSchema: GenMessage<Webhook, WebhookJson> = /*@__PURE__*/
  messageDesc(file_api_v1_webhook_service, 0);

/**
 * @generated from message memos.api.v1.CreateWebhookRequest
 */
export type CreateWebhookRequest = Message<"memos.api.v1.CreateWebhookRequest"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: string url = 2;
   */
  url: string;
};

/**
 * @generated from message memos.api.v1.CreateWebhookRequest
 */
export type CreateWebhookRequestJson = {
  /**
   * @generated from field: string name = 1;
   */
  name?: string;

  /**
   * @generated from field: string url = 2;
   */
  url?: string;
};

/**
 * Describes the message memos.api.v1.CreateWebhookRequest.
 * Use `create(CreateWebhookRequestSchema)` to create a new message.
 */
export const CreateWebhookRequestSchema: GenMessage<CreateWebhookRequest, CreateWebhookRequestJson> = /*@__PURE__*/
  messageDesc(file_api_v1_webhook_service, 1);

/**
 * @generated from message memos.api.v1.GetWebhookRequest
 */
export type GetWebhookRequest = Message<"memos.api.v1.GetWebhookRequest"> & {
  /**
   * @generated from field: int32 id = 1;
   */
  id: number;
};

/**
 * @generated from message memos.api.v1.GetWebhookRequest
 */
export type GetWebhookRequestJson = {
  /**
   * @generated from field: int32 id = 1;
   */
  id?: number;
};

/**
 * Describes the message memos.api.v1.GetWebhookRequest.
 * Use `create(GetWebhookRequestSchema)` to create a new message.
 */
export const GetWebhookRequestSchema: GenMessage<GetWebhookRequest, GetWebhookRequestJson> = /*@__PURE__*/
  messageDesc(file_api_v1_webhook_service, 2);

/**
 * @generated from message memos.api.v1.ListWebhooksRequest
 */
export type ListWebhooksRequest = Message<"memos.api.v1.ListWebhooksRequest"> & {
  /**
   * @generated from field: int32 creator_id = 1;
   */
  creatorId: number;
};

/**
 * @generated from message memos.api.v1.ListWebhooksRequest
 */
export type ListWebhooksRequestJson = {
  /**
   * @generated from field: int32 creator_id = 1;
   */
  creatorId?: number;
};

/**
 * Describes the message memos.api.v1.ListWebhooksRequest.
 * Use `create(ListWebhooksRequestSchema)` to create a new message.
 */
export const ListWebhooksRequestSchema: GenMessage<ListWebhooksRequest, ListWebhooksRequestJson> = /*@__PURE__*/
  messageDesc(file_api_v1_webhook_service, 3);

/**
 * @generated from message memos.api.v1.ListWebhooksResponse
 */
export type ListWebhooksResponse = Message<"memos.api.v1.ListWebhooksResponse"> & {
  /**
   * @generated from field: repeated memos.api.v1.Webhook webhooks = 1;
   */
  webhooks: Webhook[];
};

/**
 * @generated from message memos.api.v1.ListWebhooksResponse
 */
export type ListWebhooksResponseJson = {
  /**
   * @generated from field: repeated memos.api.v1.Webhook webhooks = 1;
   */
  webhooks?: WebhookJson[];
};

/**
 * Describes the message memos.api.v1.ListWebhooksResponse.
 * Use `create(ListWebhooksResponseSchema)` to create a new message.
 */
export const ListWebhooksResponseSchema: GenMessage<ListWebhooksResponse, ListWebhooksResponseJson> = /*@__PURE__*/
  messageDesc(file_api_v1_webhook_service, 4);

/**
 * @generated from message memos.api.v1.UpdateWebhookRequest
 */
export type UpdateWebhookRequest = Message<"memos.api.v1.UpdateWebhookRequest"> & {
  /**
   * @generated from field: memos.api.v1.Webhook webhook = 1;
   */
  webhook?: Webhook;

  /**
   * @generated from field: google.protobuf.FieldMask update_mask = 2;
   */
  updateMask?: FieldMask;
};

/**
 * @generated from message memos.api.v1.UpdateWebhookRequest
 */
export type UpdateWebhookRequestJson = {
  /**
   * @generated from field: memos.api.v1.Webhook webhook = 1;
   */
  webhook?: WebhookJson;

  /**
   * @generated from field: google.protobuf.FieldMask update_mask = 2;
   */
  updateMask?: FieldMaskJson;
};

/**
 * Describes the message memos.api.v1.UpdateWebhookRequest.
 * Use `create(UpdateWebhookRequestSchema)` to create a new message.
 */
export const UpdateWebhookRequestSchema: GenMessage<UpdateWebhookRequest, UpdateWebhookRequestJson> = /*@__PURE__*/
  messageDesc(file_api_v1_webhook_service, 5);

/**
 * @generated from message memos.api.v1.DeleteWebhookRequest
 */
export type DeleteWebhookRequest = Message<"memos.api.v1.DeleteWebhookRequest"> & {
  /**
   * @generated from field: int32 id = 1;
   */
  id: number;
};

/**
 * @generated from message memos.api.v1.DeleteWebhookRequest
 */
export type DeleteWebhookRequestJson = {
  /**
   * @generated from field: int32 id = 1;
   */
  id?: number;
};

/**
 * Describes the message memos.api.v1.DeleteWebhookRequest.
 * Use `create(DeleteWebhookRequestSchema)` to create a new message.
 */
export const DeleteWebhookRequestSchema: GenMessage<DeleteWebhookRequest, DeleteWebhookRequestJson> = /*@__PURE__*/
  messageDesc(file_api_v1_webhook_service, 6);

/**
 * @generated from service memos.api.v1.WebhookService
 */
export const WebhookService: GenService<{
  /**
   * CreateWebhook creates a new webhook.
   *
   * @generated from rpc memos.api.v1.WebhookService.CreateWebhook
   */
  createWebhook: {
    methodKind: "unary";
    input: typeof CreateWebhookRequestSchema;
    output: typeof WebhookSchema;
  },
  /**
   * GetWebhook returns a webhook by id.
   *
   * @generated from rpc memos.api.v1.WebhookService.GetWebhook
   */
  getWebhook: {
    methodKind: "unary";
    input: typeof GetWebhookRequestSchema;
    output: typeof WebhookSchema;
  },
  /**
   * ListWebhooks returns a list of webhooks.
   *
   * @generated from rpc memos.api.v1.WebhookService.ListWebhooks
   */
  listWebhooks: {
    methodKind: "unary";
    input: typeof ListWebhooksRequestSchema;
    output: typeof ListWebhooksResponseSchema;
  },
  /**
   * UpdateWebhook updates a webhook.
   *
   * @generated from rpc memos.api.v1.WebhookService.UpdateWebhook
   */
  updateWebhook: {
    methodKind: "unary";
    input: typeof UpdateWebhookRequestSchema;
    output: typeof WebhookSchema;
  },
  /**
   * DeleteWebhook deletes a webhook by id.
   *
   * @generated from rpc memos.api.v1.WebhookService.DeleteWebhook
   */
  deleteWebhook: {
    methodKind: "unary";
    input: typeof DeleteWebhookRequestSchema;
    output: typeof EmptySchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_api_v1_webhook_service, 0);

