// @generated by protoc-gen-es v2.2.3 with parameter "target=ts,json_types=true"
// @generated from file api/v1/workspace_service.proto (package memos.api.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import { file_google_api_annotations } from "../../google/api/annotations_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file api/v1/workspace_service.proto.
 */
export const file_api_v1_workspace_service: GenFile = /*@__PURE__*/
  fileDesc("Ch5hcGkvdjEvd29ya3NwYWNlX3NlcnZpY2UucHJvdG8SDG1lbW9zLmFwaS52MSJAChBXb3Jrc3BhY2VQcm9maWxlEg0KBW93bmVyGAEgASgJEg8KB3ZlcnNpb24YAiABKAkSDAoEbW9kZRgDIAEoCSIcChpHZXRXb3Jrc3BhY2VQcm9maWxlUmVxdWVzdDKXAQoQV29ya3NwYWNlU2VydmljZRKCAQoTR2V0V29ya3NwYWNlUHJvZmlsZRIoLm1lbW9zLmFwaS52MS5HZXRXb3Jrc3BhY2VQcm9maWxlUmVxdWVzdBoeLm1lbW9zLmFwaS52MS5Xb3Jrc3BhY2VQcm9maWxlIiGC0+STAhsSGS9hcGkvdjEvd29ya3NwYWNlL3Byb2ZpbGVChwEKEGNvbS5tZW1vcy5hcGkudjFCFVdvcmtzcGFjZVNlcnZpY2VQcm90b1ABWgpnZW4vYXBpL3YxogIDTUFYqgIMTWVtb3MuQXBpLlYxygIMTWVtb3NcQXBpXFYx4gIYTWVtb3NcQXBpXFYxXEdQQk1ldGFkYXRh6gIOTWVtb3M6OkFwaTo6VjFiBnByb3RvMw", [file_google_api_annotations]);

/**
 * @generated from message memos.api.v1.WorkspaceProfile
 */
export type WorkspaceProfile = Message<"memos.api.v1.WorkspaceProfile"> & {
  /**
   * The name of instance owner.
   * Format: "users/{id}"
   *
   * @generated from field: string owner = 1;
   */
  owner: string;

  /**
   * version is the current version of instance
   *
   * @generated from field: string version = 2;
   */
  version: string;

  /**
   * mode is the instance mode (e.g. "prod", "dev" or "demo").
   *
   * @generated from field: string mode = 3;
   */
  mode: string;
};

/**
 * @generated from message memos.api.v1.WorkspaceProfile
 */
export type WorkspaceProfileJson = {
  /**
   * The name of instance owner.
   * Format: "users/{id}"
   *
   * @generated from field: string owner = 1;
   */
  owner?: string;

  /**
   * version is the current version of instance
   *
   * @generated from field: string version = 2;
   */
  version?: string;

  /**
   * mode is the instance mode (e.g. "prod", "dev" or "demo").
   *
   * @generated from field: string mode = 3;
   */
  mode?: string;
};

/**
 * Describes the message memos.api.v1.WorkspaceProfile.
 * Use `create(WorkspaceProfileSchema)` to create a new message.
 */
export const WorkspaceProfileSchema: GenMessage<WorkspaceProfile, WorkspaceProfileJson> = /*@__PURE__*/
  messageDesc(file_api_v1_workspace_service, 0);

/**
 * @generated from message memos.api.v1.GetWorkspaceProfileRequest
 */
export type GetWorkspaceProfileRequest = Message<"memos.api.v1.GetWorkspaceProfileRequest"> & {
};

/**
 * @generated from message memos.api.v1.GetWorkspaceProfileRequest
 */
export type GetWorkspaceProfileRequestJson = {
};

/**
 * Describes the message memos.api.v1.GetWorkspaceProfileRequest.
 * Use `create(GetWorkspaceProfileRequestSchema)` to create a new message.
 */
export const GetWorkspaceProfileRequestSchema: GenMessage<GetWorkspaceProfileRequest, GetWorkspaceProfileRequestJson> = /*@__PURE__*/
  messageDesc(file_api_v1_workspace_service, 1);

/**
 * @generated from service memos.api.v1.WorkspaceService
 */
export const WorkspaceService: GenService<{
  /**
   * GetWorkspaceProfile returns the workspace profile.
   *
   * @generated from rpc memos.api.v1.WorkspaceService.GetWorkspaceProfile
   */
  getWorkspaceProfile: {
    methodKind: "unary";
    input: typeof GetWorkspaceProfileRequestSchema;
    output: typeof WorkspaceProfileSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_api_v1_workspace_service, 0);

